import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import MeetupList from '@/components/meetups/MeetupList'
import { MongoClient } from 'mongodb'

const inter = Inter({ subsets: ['latin'] })
export default function Home(props) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <MeetupList meetups={props.meetups} />
      </main>
    </>

  )
}
export async function getStaticProps(params) {
  const client = await MongoClient.connect(
    'mongodb+srv://tala:tala@cluster0.vljehyc.mongodb.net/meetups?retryWrites=true&w=majority')
      const dataBase = client.db()
  const meetupCollection = dataBase.collection('meetups')
  const meetups = await meetupCollection.find().toArray()

  return {
    props: {
      meetups: meetups.map((meetup) => ({
        title: meetup.title,
        address: meetup.address,
        image: meetup.image,
        description: meetup.description,
        id: meetup._id.toString()
      }))
    },
    revalidate: 1
  }
}